services:
  picamera-stream:
    build: .
    container_name: picamera-live
    restart: unless-stopped
    ports:
      - "${CAM_PORT}:8080"
    devices:
      - /dev/video0:/dev/video0
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm-cma:/dev/vcsm-cma
    privileged: true
    environment:
      - CAM_USER=${CAM_USER}
      - CAM_PASS=${CAM_PASS}
      - CAM_PORT=8080
    volumes:
      - /opt/vc/lib:/opt/vc/lib:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "--basic", "--user", "${CAM_USER}:${CAM_PASS}", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
